web/src/utils/forms.py
from src.models.models import Attendant, University
import re


def attendant_form(form, attendant=None)->Attendant:
    if attendant is None:
        fname = form['fname']
        lname = form['lname']
        academic_title = form['degree']
        if academic_title == "":
            academic_title=None
        is_banquet = form.get('is_banquet',0)
        is_tour = form.get('is_tour',0)
        email = form.get('email')
        
        if email and not is_valid_email(email):
            raise ValueError("Invalid email address")
        
        is_banquet=False if int(is_banquet)==0 else True
        is_tour=False if int(is_tour)==0 else True
        
        attendant = Attendant(fname, lname, email,  academic_title, is_banquet=is_banquet, is_tour=is_tour)
        return attendant
    else:
        attendant.fname = form['fname']
        attendant.lname = form['lname']
        attendant.academic_title = form['degree']
        is_banquet = form.get('is_banquet',0)
        is_tour = form.get('is_tour',0)
        attendant.email = form.get('email')
        attendant.is_banquet=False if int(is_banquet)==0 else True
        attendant.is_tour=False if int(is_tour)==0 else True
        return attendant

def univeristy_form(form, university=None)->University:
    if university==None:
        name = form['name']
        street = form['street']
        city = form['city']
        code = form['code']
        contry = form['country'] 
        nip = form.get('nip')
        university = University(name, street, city, code, contry, nip)
    else:
        university.name = form['name']
        university.street = form['street']
        university.city = form['city']
        university.code = form['code']
        university.contry = form['country'] 
        university.nip = form.get('nip')
    return university

def is_valid_email(email):
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

web/src/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from .config import Config


app = Flask(__name__)
app.config.from_object("src.config.Config")
db = SQLAlchemy(app)
app.secret_key = app.config['SECRET_KEY']

bcrypt = Bcrypt(app)


from src.routes.routes import *

from .models import models

web/src/controllers/admin_views.py
from datetime import date

from flask import render_template, request, redirect, flash
from sqlalchemy import desc

from src import db
from src.models.models import Attendant, University, Room, Rent
from src.utils.decorators import login_required, admin_only


@login_required
@admin_only
def analytics():
    academic_title = db.session.query(Attendant.academic_title, db.func.count(Attendant.academic_title)).group_by(
        Attendant.academic_title).order_by(desc(db.func.count(Attendant.academic_title))).all()
    
    average_cost = db.session.query(db.func.avg(Attendant.costs)).scalar()
    
    tour = db.session.query(db.func.count(Attendant.is_tour)).filter(Attendant.is_tour == True).scalar()

    banquet = db.session.query(db.func.count(Attendant.is_banquet)).filter(Attendant.is_banquet == True).scalar() 
          
    data = {
        'most_academic_title':academic_title,
        'average_cost': round(average_cost,2),
        'tour': tour,
        'banquet': banquet,
        'monday':20-get_available_rooms_no(date(2023,6,26)),
        'thuesday':20-get_available_rooms_no(date(2023,6,27)),
        'wednesday':20-get_available_rooms_no(date(2023,6,28)),
        'thursday':20-get_available_rooms_no(date(2023,6,29)),
        'friday':20-get_available_rooms_no(date(2023,6,30))
    }
    return render_template('analytics.html', data=data)

def get_available_rooms_no(date):
    return db.session.query(db.func.count(Room.room_number)).outerjoin(
    Rent, Room.room_number == Rent.room_number).filter(Rent.date == date).scalar()

@login_required
@admin_only
def attendants_list():
    attendants = Attendant.query.order_by(Attendant.att_id).all()
    universities = University.query.all()
    if request.method == 'POST':
        att_id = request.form.get('att_id')
        if att_id:
            attendant = Attendant.query.get(att_id)
            db.session.delete(attendant)
            db.session.commit()
            flash("Usunięto uczestnika.")
            
        univ_id = request.form.get('univ_id')
        if univ_id:
            university = University.query.get(univ_id)
            db.session.delete(university)
            db.session.commit()
            flash("Usunięto uniwersytet.")
        return redirect("/lista/uczestnikow", code=302)
    return render_template('attendants_list.html', attendants=attendants, universities=universities)

web/src/controllers/attendants_views.py
from flask import render_template, request, redirect, session, flash

from src import db, bcrypt
from src.models.models import Attendant, University
from src.utils.forms import attendant_form
from src.utils.decorators import login_required, admin_only

def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        attendant = Attendant.query.filter(Attendant.email==email).first()
        if attendant and bcrypt.check_password_hash(attendant.password, password):
            session['email'] = attendant.email
            return redirect('/prezentacje')
        else:
            flash("Nieprawidłowy email lub hasło")
    return render_template('login.html')

def logout():
    session.pop('email', default = None)
    flash("Wylogowano.")
    return redirect('/prezentacje')

def registration():
    universities = University.query.all()
    if request.method == 'POST':
        try:
            attendant = attendant_form(request.form)
        except ValueError as e:
            flash("Nieprawidłowe dane")
            return render_template('registration.html', universities=universities)
        password = request.form.get('password')
        attendant.password = bcrypt.generate_password_hash(password).decode('utf-8')
        univ = request.form.get('univ_name')

        if univ !="":
            univ = University.query.get(univ)
            attendant.universities.append(univ)
        session['email']=attendant.email
        db.session.add(attendant)

        db.session.commit()
        
        return redirect("/prezentacje", code=302)
    return render_template('registration.html', universities=universities)

@login_required
def edit_attendant(att_id):
    attendant = Attendant.query.get_or_404(att_id)
    universities = University.query.all()
    if request.method == 'GET':
        attendant = {
            "fname": attendant.fname,
            "lname": attendant.lname,
            "email": attendant.email,
            "academic_title":attendant.academic_title,
            "is_banquet":attendant.is_banquet,
            "is_tour":attendant.is_tour,
            "universities": attendant.universities
        }
        return render_template('attendant_update.html', attendant=attendant, universities=universities)

    elif request.method == 'POST':
        attendant = attendant_form(request.form, attendant=attendant)
        
        univ = request.form.get('univ_name')
            

        if univ !="":
            univ = University.query.get(univ)
            attendant.universities.append(univ)

        db.session.commit()
        
        return redirect("/lista/uczestnikow", code=302)
    
@login_required
def costs():
    attendant = Attendant.query.filter(Attendant.email == session['email']).first()
    if request.method == 'GET':
        attendant = {
            "fname": attendant.fname,
            "lname": attendant.lname,
            "email": attendant.email,
            "academic_title":attendant.academic_title,
            "is_banquet":attendant.is_banquet,
            "is_tour":attendant.is_tour,
            "universities": attendant.universities,
            "lectures": attendant.lectures,
            "rents": attendant.rents,
            "costs": attendant.costs
        }
        
    return render_template('costs.html', attendant=attendant)

web/src/controllers/lectures_views.py
from datetime import datetime
from flask import render_template, request, redirect, session, flash

from src import db
from src.models.models import Lecture, Attendant
from src.utils.decorators import login_required

def lectures():
    lectures = Lecture.query.order_by(Lecture.date).all()
    return render_template('lectures_list.html', lectures = lectures)

@login_required
def add_lecture():
    dates = []
    attendant = Attendant.query.filter(Attendant.email == session['email']).first()
    for date in range(26,31):
        for hour in range(8,15):
            new_date = datetime(year=2023, month=6, day=date, hour=hour)
            if Lecture.query.filter(Lecture.date==new_date).first() == None:
                dates.append(datetime(year=2023, month=6, day=date, hour=hour))
    if request.method == 'POST':
        name = request.form['name']
        att_id = attendant.att_id
        date = request.form.get('date')
        datetime_value = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
        lecture = Lecture(att_id, name, datetime_value)
        db.session.add(lecture)
        db.session.commit()
        return redirect("/prezentacje", code=302)
    return render_template('lecture_form.html', dates=dates)

@login_required
def edit_lecture(lecture_id):
    lecture = Lecture.query.get_or_404(lecture_id)
    attendant = Attendant.query.filter(Attendant.email == session['email']).first()
    if lecture.att_id != attendant.att_id:
        flash("Nie jesteś autorem.")
        return redirect("/prezentacje")
    dates = []
    for date in range(26,31):
        for hour in range(8,15):
            new_date = datetime(year=2023, month=6, day=date, hour=hour)
            if Lecture.query.filter(Lecture.date==new_date).first() == None:
                dates.append(datetime(year=2023, month=6, day=date, hour=hour))
    if request.method == 'GET':
        lecture = {
            "lecture_id" : lecture.lecture_id,
            "name": lecture.name,
            "date": lecture.date
        }
        return render_template('lecture_update.html', lecture=lecture, dates=dates)

    elif request.method == 'POST':
        lecture.att_id = request.form.get('att_id', lecture.att_id)
        lecture.name = request.form.get('name', lecture.name)
        if not lecture.date == request.form.get('date', lecture.date):
            lecture.date = request.form.get('date')
        db.session.commit()
        
        return redirect("/prezentacje", code=302)

web/src/controllers/rooms_views.py
from datetime import datetime
from flask import render_template, request, session

from src import db
from src.models.models import Attendant, Room, Rent
from src.utils.decorators import login_required

@login_required
def rooms():
    rooms = Room.query.order_by(Room.room_number).all()
    attendant = Attendant.query.filter(Attendant.email == session['email']).first()
    if request.method == 'POST':
        room_number_day = request.form['reservarion']
        room_number, day = room_number_day.split('&')
        rent = Rent(int(room_number), attendant.att_id, datetime(day=int(day), year=2023, month=6))
        db.session.add(rent)
        db.session.commit()
    return render_template('room_list.html', rooms = rooms)

web/src/controllers/university_views.py
from flask import render_template, request, redirect

from src import db
from src.models.models import University
from src.utils.forms import univeristy_form
from src.utils.decorators import login_required


def add_university():
    if request.method == 'POST':
        university = univeristy_form(request.form)
        
        db.session.add(university)
        db.session.commit()
        
        return redirect("/rejestracja", code=302)
    return render_template('university_form.html')


@login_required
def edit_university(univ_id):
    university = University.query.get_or_404(univ_id)

    if request.method == 'GET':
        university = {
            "univ_id" : university.univ_id,
            "name": university.name,
            "street": university.street,
            "city": university.city,
            "code": university.code,
            "country": university.country,
            "nip": university.NIP
        }
        return render_template('university_update.html', university=university)

    elif request.method == 'POST':
        university = univeristy_form(request.form, university)
        db.session.commit()
        
        return redirect("/prezentacje", code=302)

web/src/routes/routes.py
from datetime import datetime
from flask import Blueprint

from src import app

from src.controllers.lectures_views import lectures, add_lecture, edit_lecture
from src.controllers.attendants_views import registration, edit_attendant, costs, login, logout
from src.controllers.rooms_views import rooms
from src.controllers.university_views import add_university, edit_university
from src.controllers.admin_views import attendants_list, analytics


konf = Blueprint('konf', __name__)

konf.route('/prezentacje', methods=['GET'])(lectures)
konf.route('/dodaj/prezentacje', methods=['GET', 'POST'])(add_lecture)
konf.route('/edytuj/prezentacje/<lecture_id>', methods=['GET', 'POST', 'DELETE'])(edit_lecture)

konf.route('/lista/uczestnikow', methods=['GET','POST'])(attendants_list)
konf.route('/statystyka', methods = ['GET', 'POST'])(analytics)

konf.route('/rejestracja', methods = ['GET','POST'])(registration)
konf.route('/login', methods=['GET', 'POST'])(login)
konf.route('/logout', methods=['GET', 'POST'])(logout)
konf.route('/edytuj/uczestnika/<att_id>', methods = ['GET','POST'])(edit_attendant)
konf.route('/koszty', methods = ['GET'])(costs)

konf.route('/hotel', methods=['GET','POST'])(rooms)

konf.route('/dodaj/uniwersytet', methods=['GET', 'POST'])(add_university)
konf.route('/edytuj/uniwerytet/<univ_id>', methods = ['GET','POST'])(edit_university)

app.register_blueprint(konf, url_prefix='/')

web/src/templates/analytics.html
{% extends 'base.html' %}

{% block content %}

<div> Wykształcenie uczestników:  </div>
{% for i in data['academic_title']%} 
<div>{{i[0]}}, ilość: {{i[1]}}</div>
{% endfor %}
<div> Średni koszt przypadający na uczestnika: {{data['average_cost']}} zł</div>

<div> Ilość osób biorących udział w wycieczce: {{data['tour']}}</div>

<div> Ilość osób biorących udział w bankiecie: {{data['banquet']}}</div>

<div> Ilość dostępnych pokoi 26.06.2023: {{data['monday']}}</div>

<div> Ilość dostępnych pokoi 27.06.2023: {{data['thuesday']}}</div>

<div> Ilość dostępnych pokoi 28.06.2023: {{data['wednesday']}}</div>

<div> Ilość dostępnych pokoi 29.06.2023: {{data['thursday']}}</div>

<div> Ilość dostępnych pokoi 30.06.2023: {{data['friday']}}</div>

{% endblock %}

web/src/templates/attendant_update.html
{% extends 'base.html' %}

{% block content %}
    <form method = "post">
      <div class="title">
        <i class="fas fa-pencil-alt"></i> 
        <h2>Edytuj uczestnika</h2>
      </div>
      <div class="info">
        <input class="fname" type="text" name="fname" value={{attendant['fname']}}>
        <input class="lname" type="text" name="lname" value={{attendant['lname']}}>
        <input class="lname" type="text" name="email" value={{attendant['email']}}>
        <select name = "degree">
          <option value={{attendant['academic_title']}} selected>{{attendant['academic_title']}}</option>
          <option value="">Brak</option>
          <option value="Licencjat">Licencjat</option>
          <option value="Inżynier">Inżynier</option>
          <option value="Magister">Magister</option>
          <option value="Doktor">Doktor</option>
          <option value="Profesor">Profesor</option>
          <option value="">Inne</option>
        </select>
        <select name = "univ_name" id="SelectOption">
          <option value="" selected>{{attendant['universities'][0]}}</option>
          <option value="">Brak</option>
          {% for university in universities %}
          <option value={{ university.univ_id }}>{{ university }}</option>
          {% endfor %}
          <option value = "add">Nie ma twojego uniwersytetu? Dodaj go do bazy</option>
        </select>
        <div style="display:flex">
          <p>Chcę uczestniczyć w bankiecie.</p>  
          <input type='checkbox' value='1' name='is_banquet'  {% if attendant['is_banquet'] %} checked {% endif %}>
        </div>
        <div style="display:flex">
          <p>Chcę uczestniczyć w wycieczce.</p>  
          <input type='checkbox' value='1' name='is_tour'>
        </div>
      </div>
      <button type="submit">Zaakcaptuj dane</button>
    </form>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#SelectOption').change(function() {
        var val = $(this).val();
        if (val === 'add') {
          window.location.href = '/dodaj/uniwersytet';
        }
      });
    });
  </script>
  {% endblock %}

web/src/templates/attendants_list.html
{% extends 'base.html' %}

{% block content %}


<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Imię i nazwisko</th>
      <th>Tytuł naukowy</th>
      <th>Email</th>
      <th>Uniwersytet</th>
      <th>Udział w bankiecie</th>
      <th>Udział w wycieczce</th>
      <th>Koszty</th>
    </tr>
  </thead>
  <tbody>
      <form method = 'post'>
      {% for attendant in attendants %}
    <tr>
      <td>{{ attendant.att_id }}</td>        
      <td>{{ attendant.fname }} {{ attendant.lname }}</td>
      <td>{{ attendant.academic_title }}</td>
      <td>{{ attendant.email }}</td>
      <td>{{ attendant.universities }}</td>
      <td>{{ attendant.is_banquet }}</td>
      <td>{{ attendant.is_tour }}</td>
      <td>{{ attendant.costs }}</td>
      <td>          <a class="nav-link" href="{{ url_for('konf.costs', att_id=attendant.att_id) }}">Koszty</a>
        <button name = "att_id" value = {{ attendant.att_id }} class="btn btn-secondary">Usuń</button>
      <a href="{{ url_for('konf.edit_attendant', att_id=attendant.att_id) }}" class="btn btn-secondary">Edytuj</a>
      </td>
    </tr>
    {% endfor %}
  </form>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nazwa Uniwersytetu</th>
      <th>Ulica</th>
      <th>Miasto</th>
      <th>Kraj</th>
      <th>Uczestnicy</th>
      <th>NIP</th>
    </tr>
  </thead>
  <tbody>
      <form method = 'post'>
      {% for university in universities %}
    <tr>
      <td>{{ university.univ_id }}</td>
      <td>{{ university.name }}</td>
      <td>{{ university.street }} </td>
      <td>{{ university.code }} {{ university.city }}</td>
      <td>{{ university.country }}</td>
      <td>{{ university.attendants }}</td>
      <td>{{ university.NIP }}</td>
      <td><button name = "univ_id" value = {{ university.univ_id }} class="btn btn-secondary">Usuń</button>
        <a href="{{ url_for('konf.edit_university', univ_id=university.univ_id) }}" class="btn btn-secondary">Edytuj</a>
      </td>
    </tr>
    {% endfor %}
  </form>
  </tbody>
</table>
{% endblock %}

web/src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Konferencja</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/style.css') }}">

  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if not session['email']%}
    <a class="navbar-brand" href="/rejestracja">Zapisz się!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/login">Zaloguj się.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      
      <span class="navbar-toggler-icon"></span>
    </button>
    {% else %}
    <a class="navbar-brand" href="/logout">Wyloguj się.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      
      <span class="navbar-toggler-icon"></span>
    </button>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/prezentacje">Lista Prezentacji <span class="sr-only">(current)</span></a>
        </li>
        {% if session['email']%}
        <li class="nav-item">
          <a class="nav-link" href="/hotel">Hotel</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('konf.costs')}}">Koszty</a>
        </li>
        {% endif %}
        {% if session['email'] == 'admin@admin.pl' %}        
        <li class="nav-item">
          <a class="nav-link disabled" href="/lista/uczestnikow">Lista Uczestników i Uczelni</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="/statystyka">Statystyka</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-secondary" role="alert">
      {% for message in messages %}
        {{ message }}</li>
      {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
    {% block content %} 
    
    {% endblock %}
    </div>
  </body>
</html>

web/src/templates/costs.html
{% extends 'base.html' %}

{% block content %}
<div class="title">
  <h2>Suma twoich kosztów: </h2>
</div>
<div class="info">
  <p>{{attendant['academic_title']}} {{attendant['fname']}} {{attendant['lname']}}</p>
  <p></p>
  <p>{{attendant['email']}}</p>
  <p>{% if attendant['is_banquet']==True%} Udział w bankiecie {% endif %}</p>
  <p>{% if attendant['is_tour']== True%} Udział w wycieczce {% endif %}</p>

      {% for lecture in attendant['lectures'] %}
      <p>{{lecture}}</p>
      {% endfor %}
      {% for rent in attendant['rents'] %}
      <p>{{rent}}</p>
      {% endfor %}
    <p> Razem: {{attendant['costs']}} zł</p>
</div>
{% endblock %}

web/src/templates/lecture_form.html
{% extends 'base.html' %}

{% block content %}

 
<body>
  <form action="/dodaj/prezentacje" method="post">
    <div class="title">
      <i class="fas fa-pencil-alt"></i> 
      <h2>Zapisz swoją prezentację</h2>
    </div>
    <div class="info">
      <label for="name">Tytuł:</label>
      <input type="text" id="name" name="name" placeholder="Wprowadź tytuł">
      
      <label for="date">Data:</label>
      <select id="date" name="date">
        <option selected disabled>Wybierz dostępną datę</option>
        {% for date in dates %}
          <option value="{{ date }}">{{ date }}</option>
        {% endfor %}
      </select>
    </div>

    <button type="submit">Wyślij</button>
  </form>
{% endblock %}

web/src/templates/lecture_update.html
{% extends 'base.html' %}

{% block content %}

 
<body>
  <form method="post">
    <div class="title">
      <i class="fas fa-pencil-alt"></i> 
      <h2>Edytujesz prezentacje</h2>
    </div>
    <div class="info">
      <label for="name">Tytuł:</label>
      <input type="text" id="name" name="name" value="{{lecture['name']}}">
      
      <label for="date">Data:</label>
      <select id="date" name="date">
        <option value="{{lecture['date']}}">{{lecture['date']}}</option>
        {% for date in dates %}
          <option value="{{ date }}">{{ date }}</option>
        {% endfor %}
      </select>
    </div>

    <button type="submit">Wyślij</button>
  </form>
{% endblock %}

web/src/templates/lectures_list.html
{% extends 'base.html' %}

{% block content %}

  <title>Kalendarz Konferencji</title>
  <style>
    
    h1 {
      text-align: center;
      margin-top: 20px;
    }
    
    table {
      border-collapse: collapse;
      width: 100%;
      margin-top: 20px;
    }
    
    th, td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    th {
      background-color: #f2f2f2;
    }
    
    td.today {
      background-color: #f9f9f9;
      font-weight: bold;
    }
    
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }
    
    li {
      margin-bottom: 10px;
    }
    
    a.button {
      display: block;
      text-align: center;
      margin: 20px auto;
      padding: 10px 20px;
      background-color: grey;
      color: white;
      text-decoration: none;
      border-radius: 3px;
    }
    
    a.button:hover {
      background-color: #f2f2f2;
      color:black;
    }
  </style>
</head>
<body>
  <h1>Kalendarz Konferencji</h1>
  <table>
    <tr>
      <th>26.06.2023 Poniedziałek</th>
      <th>27.06.2023 Wtorek</th>
      <th>28.06.2023 Środa</th>
      <th>29.06.2023 Czwartek</th>
      <th>30.06.2023 Piątek</th>
    </tr>
    <tr>
      <td>
        <ul>
          {% for lecture in lectures %}
            {% if lecture.date.day == 26 %}
              <li>{{ lecture.date.hour }}.00-{{ lecture.date.hour+1 }}.00 <a href="{{ url_for('konf.edit_lecture', lecture_id=lecture.lecture_id) }}">{{ lecture.name }}</a>. 
                <br>Autor: {{ lecture.attendant }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
          {% for lecture in lectures %}
            {% if lecture.date.day == 27 %}
              <li>{{ lecture.date.hour }}.00-{{ lecture.date.hour+1 }}.00 <a href="{{ url_for('konf.edit_lecture', lecture_id=lecture.lecture_id) }}">{{ lecture.name }}</a>. <br>Autor: {{ lecture.attendant }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
          {% for lecture in lectures %}
            {% if lecture.date.day == 28 %}
              <li>{{ lecture.date.hour }}.00-{{ lecture.date.hour+1 }}.00 <a href="{{ url_for('konf.edit_lecture', lecture_id=lecture.lecture_id) }}">{{ lecture.name }}</a>. <br>Autor: {{ lecture.attendant }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
          {% for lecture in lectures %}
            {% if lecture.date.day == 29 %}
              <li>{{ lecture.date.hour }}.00-{{ lecture.date.hour+1 }}.00 <a href="{{ url_for('konf.edit_lecture', lecture_id=lecture.lecture_id) }}">{{ lecture.name }}</a>. <br>Autor: {{ lecture.attendant }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
      <td>
        <ul>
          {% for lecture in lectures %}
            {% if lecture.date.day == 30 %}
              <li>{{ lecture.date.hour }}.00-{{ lecture.date.hour+1 }}.00 <a href="{{ url_for('konf.edit_lecture', lecture_id=lecture.lecture_id) }}">{{ lecture.name }}</a>. <br>Autor: {{ lecture.attendant }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </td>
    </tr>
  </table>
  <a href="/dodaj/prezentacje" class="button">Dodaj Prezentację</a>
{% endblock %}

web/src/templates/login.html
{% extends 'base.html' %}

{% block content %}

  <div class="main-block">
    <div class="left-part">
      <i class="fas fa-graduation-cap"></i>
      <h1>Zarejestruj się na naszą konferencję</h1>
      <p>Zobacz jakie prezentacje zostały już zarejestrowane.</p>
      <div class="btn-group">
        <a class="btn-item" href="/prezentacje">Lista prezentacji</a>
      </div>
    </div>
    <form method = "post">
      <div class="title">
        <i class="fas fa-pencil-alt"></i> 
        <h2>Zaloguj się tutaj</h2>
      </div>
      <div class="info">
        <input class="fname" type="text" name="email" placeholder="Email">
        <input class="lname" type="password" name="password" placeholder="Hasło">
      </div>
      <button type="submit">Zaloguj się</button>
    </form>
  </div>
  </div>
  {% endblock %}